# Generated by Django 5.1.4 on 2024-12-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Default Product', max_length=50),
            preserve_default=False,
        ),
    ]
